name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker to use Minikube's Docker daemon
      shell: pwsh
      run: |
        echo "Configuring Docker to use Minikube's Docker daemon..."
        $envVars = & minikube -p minikube docker-env --shell powershell
        if ($LASTEXITCODE -eq 0) {
          Write-Output "Minikube environment variables:"
          Write-Output $envVars
          Invoke-Expression $envVars
        } else {
          Write-Error "Failed to configure Docker to use Minikube's Docker daemon."
        }

    - name: Start Minikube
      shell: powershell
      run: |
          Write-Output "Starting Minikube..."
          minikube start --driver=docker
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to start Minikube"
            exit 1
          }
          Write-Output "Minikube started successfully"

    - name: Verify Minikube and Docker
      shell: powershell
      run: |
          Write-Output "Checking Minikube and Docker installation..."
          minikube version
          docker --version
          docker info --format '{{.ServerVersion}}'
          Write-Output "Checking Minikube status..."
          $status = minikube status -p minikube
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Minikube is not running or accessible"
            exit 1
          }
          Write-Output "Minikube is running"

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
          Write-Output "Configuring Docker to use Minikube's environment..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to set up Minikube Docker environment"
            exit 1
          }
          Write-Output "Docker environment set up successfully"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Docker image
      run: docker build -t azghanahmad/e-ticket-backend:latest ./app/backend

    - name: Build Frontend Docker image
      run: docker build -t azghanahmad/e-ticket-frontend:latest ./app/frontend
    
    - name: Push Backend Image to Docker Hub
      run: docker push azghanahmad/e-ticket-backend:latest

    - name: Push Frontend Image to Docker Hub
      run: docker push azghanahmad/e-ticket-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/deployment-backend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/deployment-frontend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/service-backend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/service-frontend.yaml --namespace=scd-project