name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube
      shell: powershell
      run: |
        Write-Output "Starting Minikube..."
        minikube start
        
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to start Minikube"
          exit 1
        }

    - name: Wait for Minikube to be ready
      shell: powershell
      run: |
        $retries = 10
        for ($i = 0; $i -lt $retries; $i++) {
          $status = minikube status -p minikube
          if ($status -match "host: Running") {
            Write-Output "Minikube is ready"
            break
          }
          Write-Output "Waiting for Minikube... ($i/$retries)"
          Start-Sleep -Seconds 10
          if ($i -eq $retries - 1) {
            Write-Error "Minikube did not become ready in time"
            exit 1
          }
        }

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        Write-Output "Configuring Docker to use Minikube's Docker daemon (safe mode)..."

        $envOutput = & minikube -p minikube docker-env --shell powershell
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to get Minikube Docker environment"
          exit 1
        }

        $envLines = $envOutput -split "`n"
        foreach ($line in $envLines) {
          if ($line -match '^\$Env:([^ ]+) = "([^"]+)"$') {
            $name = $matches[1]
            $value = $matches[2]
            Write-Output "Setting environment variable: $name"
            [System.Environment]::SetEnvironmentVariable($name, $value, "Process")
          }
        }

        Write-Output "Docker environment set up successfully"


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Docker image
      run: docker build -t azghanahmad/e-ticket-backend:latest ./app/backend

    - name: Build Frontend Docker image
      run: docker build -t azghanahmad/e-ticket-frontend:latest ./app/frontend

    - name: Push Backend Image to Docker Hub
      run: docker push azghanahmad/e-ticket-backend:latest

    - name: Push Frontend Image to Docker Hub
      run: docker push azghanahmad/e-ticket-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/deployment-backend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/deployment-frontend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/service-backend.yaml --namespace=scd-project
        kubectl apply -f kubernetes/service-frontend.yaml --namespace=scd-project